name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}

    - name: Deploy
      uses: Nirweint/cards-project@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: build
